module EPUB
  GENRES = [
    "adventure stories",
    "adventure stories, american",
    "adventure stories, australian",
    "adventure stories, english",
    "adventure stories, french",
    "ballad opera",
    "ballad operas",
    "ballads",
    "ballads, english",
    "ballads, french",
    "ballads, scots",
    "bibliography",
    "biography",
    "black humor",
    "botany",
    "chinese classics",
    "chinese drama",
    "chinese drama (tragedy)",
    "chinese fiction",
    "chinese language",
    "chinese literature",
    "chinese poetry",
    "chinese prose literature",
    "christmas stories",
    "classical literature",
    "classical philology",
    "classical poetry",
    "comedies",
    "comedy",
    "commentaries",
    "controversial literature",
    "crime",
    "danish fiction",
    "danish literature",
    "danish poetry",
    "detective and mystery stories",
    "detective and mystery stories, american",
    "detective and mystery stories, chinese",
    "detective and mystery stories, english",
    "detective and mystery stories, french",
    "detective and mystery stories, german",
    "diaries",
    "diary fiction",
    "didactic drama",
    "didactic fiction",
    "didactic poetry",
    "didactic poetry, latin",
    "doctrinal and controversial works",
    "documents",
    "domestic fiction",
    "drama",
    "dutch drama",
    "dutch fiction",
    "dutch language",
    "dutch literature",
    "easter stories",
    "egyptian literature",
    "encyclopedias and dictionaries",
    "english drama",
    "english drama (comedy)",
    "english essays",
    "english fiction",
    "english language",
    "english literature",
    "english periodicals",
    "english poetry",
    "english prose literature",
    "english wit and humor",
    "english wit and humor, pictorial",
    "epic literature",
    "epic literature, irish",
    "epic poetry",
    "epic poetry, english",
    "epic poetry, english (old)",
    "epic poetry, french",
    "epic poetry, german",
    "epic poetry, greek",
    "epic poetry, italian",
    "epic poetry, latin",
    "epic poetry, sanskrit",
    "epistolary fiction",
    "epistolary fiction, english",
    "erotic literature",
    "erotic literature, american",
    "erotic literature, chinese",
    "erotic literature, german",
    "erotic poetry, french",
    "erotic stories",
    "erotic stories, chinese",
    "essays",
    "excerpts",
    "fables",
    "fables, american",
    "fables, english",
    "fables, french",
    "fables, greek",
    "fables, latin",
    "fables, polish",
    "fables, spanish",
    "facsimiles",
    "fairy plays",
    "fairy poetry",
    "fairy tales",
    "fantasy",
    "fantasy fiction",
    "fantasy fiction, american",
    "fantasy fiction, chinese",
    "fantasy fiction, english",
    "fantasy fiction, french",
    "fantasy fiction, italian",
    "fantasy poetry",
    "fantasy poetry, american",
    "fiction",
    "finnish drama",
    "finnish poetry",
    "folk dance music",
    "folk drama, chinese",
    "folk literature, english",
    "folk literature, philippine",
    "folk poetry, american",
    "folk songs, english",
    "folk songs, french",
    "folk songs, welsh",
    "folklore",
    "german drama",
    "german fiction",
    "german language",
    "german literature",
    "german poetry",
    "german wit and humor",
    "ghost stories",
    "ghost stories, american",
    "ghost stories, chinese",
    "ghost stories, english",
    "ghost stories, indic (english)",
    "ghost stories, scottish",
    "gothic fiction",
    "greek drama",
    "greek drama (comedy)",
    "greek drama (satyr play)",
    "greek drama (tragedy)",
    "greek poetry",
    "greek poetry, modern",
    "guide-books",
    "guidebooks",
    "handbooks, manuals, etc.",
    "handbooks, vade-mecums, etc.",
    "historical drama",
    "historical fiction",
    "historical fiction, american",
    "historical fiction, english",
    "historical poetry",
    "history",
    "history, ancient",
    "history, local",
    "history, military",
    "history, modern",
    "history, naval",
    "horror tales",
    "horror tales, american",
    "horror tales, english",
    "horror tales, french",
    "humor",
    "humor, caricatures, etc.",
    "humorous poetry",
    "humorous poetry, american",
    "humorous poetry, english",
    "humorous stories",
    "humorous stories, american",
    "humorous stories, canadian",
    "humorous stories, english",
    "hymns",
    "hymns, danish",
    "hymns, english",
    "hymns, german",
    "hymns, greek",
    "hymns, greek (classical)",
    "hymns, latin",
    "hymns, welsh",
    "illustrated children's books",
    "illustrated periodicals",
    "imagist poetry",
    "indian drama",
    "indian literature",
    "indian mythology",
    "indian philosophy",
    "indic drama",
    "indic poetry",
    "indic poetry (english)",
    "irish drama",
    "irish literature",
    "irish poetry",
    "irish wit and humor",
    "irish-american wit and humor",
    "italian drama",
    "italian drama (comedy)",
    "italian fiction",
    "italian language",
    "italian poetry",
    "italian wit and humor",
    "japanese language",
    "japanese poetry",
    "jewish fiction",
    "jewish literature",
    "journalism",
    "juvenile and popular literature",
    "juvenile fiction",
    "juvenile fiction.",
    "juvenile literature",
    "juvenile poetry",
    "kashubian literature",
    "latin literature",
    "latin poetry",
    "letters",
    "logic",
    "logic, ancient",
    "logic, symbolic and mathematical",
    "love poetry",
    "love poetry, canadian",
    "love poetry, romance",
    "love stories",
    "love stories, american",
    "love stories, chinese",
    "love stories, english",
    "love stories, french",
    "love stories, german",
    "love-letters",
    "manuals",
    "manuscripts",
    "manuscripts, english",
    "manuscripts, latin",
    "manuscripts, maya",
    "manuscripts, medieval",
    "manuscripts, renaissance",
    "medical fiction",
    "methods",
    "methods and manuals",
    "military history, medieval",
    "military history, modern",
    "mystery and detective stories",
    "mystery fiction",
    "myth",
    "mythology",
    "mythology, assyro-babylonian",
    "mythology, celtic",
    "mythology, chinese",
    "mythology, classical",
    "mythology, classical, in art",
    "mythology, egyptian",
    "mythology, finno-ugrian",
    "mythology, germanic",
    "mythology, greek",
    "mythology, japanese",
    "mythology, norse",
    "nahuatl poetry",
    "natural history",
    "nature stories",
    "naval history",
    "nonsense verses",
    "nonsense verses, english",
    "nursery rhymes",
    "nursery rhymes, american",
    "nursery rhymes, english",
    "occult fiction",
    "occult fiction, english",
    "old norse literature",
    "old norse poetry",
    "parodies",
    "parodies, american",
    "parodies, imitations, etc.",
    "pastoral drama",
    "pastoral drama, italian",
    "pastoral fiction",
    "pastoral fiction, french",
    "pastoral poetry",
    "pastoral poetry, latin",
    "periodicals",
    "personal narratives",
    "personal narratives, american",
    "personal narratives, australian",
    "personal narratives, austrian",
    "personal narratives, british",
    "personal narratives, canadian",
    "personal narratives, confederate",
    "personal narratives, english",
    "personal narratives, french",
    "personal narratives, german",
    "personal narratives, irish",
    "personal narratives, jamaican",
    "personal narrativies",
    "philosophy",
    "philosophy, american",
    "philosophy, ancient",
    "philosophy, arab",
    "philosophy, chinese",
    "philosophy, confucian",
    "philosophy, english",
    "philosophy, french",
    "philosophy, german",
    "philosophy, hindu",
    "philosophy, jewish",
    "philosophy, medieval",
    "philosophy, modern",
    "poetry",
    "poetry of places",
    "poetry, dutch",
    "poetry, english",
    "poets",
    "poets, american",
    "poets, chinese",
    "poets, english",
    "poets, french",
    "poets, german",
    "poets, irish",
    "poets, latin",
    "poets, scottish",
    "political fiction",
    "political poetry",
    "political science",
    "popular works",
    "portuguese drama",
    "portuguese fiction",
    "portuguese literature",
    "portuguese poetry",
    "portuguese wit and humor",
    "prayer-books and devotions",
    "prayers",
    "prayers and devotions",
    "psychological fiction",
    "religious fiction",
    "rhetoric",
    "rhetoric, ancient",
    "romance literature",
    "romances",
    "romances, english",
    "russian drama",
    "russian fiction",
    "russian literature",
    "russian poetry",
    "sacred books",
    "sacred texts",
    "science",
    "science fiction",
    "science fiction, american",
    "science fiction, english",
    "sea poetry",
    "sea songs",
    "sea stories",
    "sea stories, american",
    "sea stories, english",
    "sermons",
    "sermons, american",
    "sermons, english",
    "short stories",
    "short stories, american",
    "short stories, australian",
    "short stories, bengali",
    "short stories, brazilian",
    "short stories, canadian",
    "short stories, chinese",
    "short stories, dutch",
    "short stories, english",
    "short stories, french",
    "short stories, german",
    "short stories, icelandic",
    "short stories, irish",
    "short stories, italian",
    "short stories, new zealand",
    "short stories, spanish",
    "short story",
    "spanish drama",
    "spanish fiction",
    "spanish poetry",
    "stories in rhyme",
    "swedish drama",
    "swedish poetry",
    "tales",
    "tales, german",
    "tales, medieval",
    "tragedies",
    "tragedy",
    "tragicomedy",
    "translations",
    "translations from german",
    "translations into catalan",
    "translations into dutch",
    "translations into english",
    "translations into esperanto",
    "translations into finnish",
    "translations into french",
    "translations into german",
    "translations into portuguese",
    "translations into spanish",
    "welsh literature",
    "welsh poetry",
    "western stories",
    "wit and humor",
    "wit and humor, juvenile",
    "wit and humor, pictorial"
  ].freeze
end