# AlbiteBOOKS settings
# ====================

# Site title
title: Albite BOOKS

# Mobile version: activate using the user agent or the subdomain
# ==============================================================
#
# using the subdomain if true (e.g. http://m.albite.vlexofree.com), or the user-agent header if false
mobile_by_subdomain: false

# Count of books showed at the homepage
homepage_book_count: 3

# App's Secret Token
# ==================
#
# Your secret key for verifying cookie session data integrity.
# If you change this key, all old sessions will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
secret_token: some_random_number_goes_here

# True, if new users can sign up
# ==============================
can_add_users: false

# Hide letter-indices, therefore showing all books (useful if there is too little content)
# ========================================================================================
hide_author_index: false
hide_book_index: false

# SMTP mail (gmail settings preset)
# =================================
smtp:
  address: smtp.gmail.com
  port: 587
  authentication: plain
  enable_starttls_auto: true
  user_name: your_username@gmail.com
  password: your_password

# Mail from field
# ===============
mail_from: your_username@gmail.com

# Recaptcha
# =========
recaptcha_public_key: recaptcha_public_key_goes_here
recaptcha_private_key: recaptcha_private_key_goes_here

# UserVoice Feedback button/form
# ===============================
uservoice:
  key: your_key
  host: your_key.uservoice.com
  forum: your_forum_id_number

# DISQUS Options
# ==============
disqus_shortname: your_disqus_shortname
